config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :user_achievements
  resources :user_events
  resources :achievements
  resources :locations
  resources :events
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  patch '/attending', to: "events#update"
  get '/home', to: 'application#home', as: 'home'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/users', to: 'users#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  post '/achieved', to: 'events#achieved'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :category
  has_many :user_achievements
  has_many :users, through: :user_achievements
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
  has_many :achievements
  # def self.uniq_list
  #   arr = []
  #   self.all.each do |category|
  #     arr << category.name
  #   end
  #   arr.uniq
  # end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events
  has_many :users, through: :user_events
  belongs_to :location
  belongs_to :category
  validates :title, presence: true
  validates :description, presence: true

  def self.uniq_event_type_list
    arr = []
    self.all.each do |event|
      arr << event.event_type.to_s
    end
    arr.uniq
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_events
  has_many :events, through: :user_events
  has_many :user_achievements
  has_many :achievements, through: :user_achievements

  validates :username, uniqueness: true
  has_secure_password

  def my_achievements
    sum = 0
    self.achievements.uniq.each do |achievement|
      sum += achievement.points
    end
    sum
  end

end

app/models/user_achievement.rb
class UserAchievement < ApplicationRecord
  belongs_to :user
  belongs_to :achievement
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user

 def current_user
   User.find_by({ id: session[:user_id] })
 end

 def logged_in?
   !!current_user
 end

 def home
   render :home
 end

 def authorized
   redirect_to login_path unless logged_in?
 end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    if params[:category] && params[:category][:id]
      @events = Event.where(category_id: params[:category][:id])
    else
      @events = Event.all
    end
  end

  def show
    @event = Event.find(params[:id])
    @achievement = Achievement.new
    if params[:event] && params[:event][:user_events]
      if params[:event][:user_events] == "Attending"
        @userevent = UserEvent.create(user_id: current_user.id, event_id: @event.id, status: "Attending")
      else
        @userevent = UserEvent.create(user_id: current_user.id, event_id: @event.id, status: "Interested")
      end
    end
  end

  def achieved
    @achievement = Achievement.find_by(id: params[:achievement][:id])
    if params[:achievement] && params[:achievement][:id]
      if params[:achievement][:id] != ""
        params[:achievement][:id].each do |aid|
          if aid != ""
            @userachievement = UserAchievement.create(user_id: current_user.id, achievement_id: aid, status: "Complete")
          end
        end
        if @userachievement.valid?
          flash[:notice] = 'ACHIEVEMENT UNLOCKED!'
          redirect_to event_path(params[:event][:id])
        end
      end
    end
  end

  def new
    @event = Event.new
    @location = @event.location
  end

  def create
    @event = Event.new(event_params)
    if params[:event] && params[:event][:location_id] != ""
      @event.location = Location.find_by(id: params[:event][:location_id])
    else
      @event.location = Location.create(name: params[:name], address: params[:address], borough: params[:borough])
    end
    if params[:event] && params[:event][:category_id] != ""
      @event.category = Category.find_by(id: params[:event][:category_id])
    else
      @event.category = Category.create(name: params[:type])
    end
    if @event.valid?
      @event.save
      redirect_to @event
    else
      flash[:errors] = @event.errors.full_messages
      redirect_to new_event_path
    end
  end

  def update
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to @event
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location_id, :event_type, :category_id, :user_events, :user_achievements, :category, :event_id)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    render :new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = 'Invalid username or password'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'logged out'
    redirect_to login_path
  end
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  def new
    @user_event = UserEvent.new
  end

  def create
    @user_event = UserEvent.create(user_event_params)
    session[:user_id] = @user.id
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    session[:user_id] = @user.id
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'You deleted your account'
    redirect_to login_path
  end


    private

    def user_params
      params.require(:user).permit(:username, :password, :name, :age)
    end
  end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/user_achievements_helper.rb
module UserAchievementsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.erb
<div class="event_index">
  <html>
  <head>
  <meta charset='utf-8' />
  <title>Add a marker using a place name</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />
  <style>
  body { margin:0; padding:0; }
  #map { position:fixed; top:0; right:0; bottom:0; width:50%; }
  </style>
  </head>
  <!-- END OF MAP HEADER -->
  <div class="header">
    <h1>Events</h1>
  </div>

  <div class="search_bar">
    <%= form_tag events_path, :method => :get, :class => 'form-search' do %>
        <span id="search_text">Search: </span><%= collection_select :category, :id, Category.all, :id, :name, {:prompt => "Select Category"} %>
        <%= submit_tag "Search", :class => 'search_button'%>
    <% end %>
  </div>
  <br>
  <div style="border-radius:5px;"class="key">
    <div class="col1">
      <div class="col sm 4" style="background-color:red; width: 100%; height: 35px; vertical-align:center; border: solid white;text-shadow: 0 0 4px black;">Happy Hour</div>
      <div class="col sm 4" style="background-color:magenta; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Cats</div>
      <div class="col sm 4" style="background-color:green; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Park</div>
    </div>
    <div class="col2">
      <div class="col sm 4" style="background-color:blue; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;">Escape Room</div>
      <div class="col sm 4" style="background-color:purple; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Code</div>
      <div class="col sm 4" style="background-color:yellow; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Restaurant</div>
    </div>
    <div class="col3">
      <div class="col sm 4" style="background-color:orange; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Store</div>
      <div class="col sm 4" style="background-color:cyan; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Arcade </div>
      <div class="col sm 4" style="background-color:black; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Other</div>
    </div>

  </div>
  <br>

  <% @events.each do |event| %>
    <ul>
      <div class="events">
        <%= link_to event.title, event , :class => "links"%><br>
        <strong>Location: </strong><%= event.location.name %><br>
        <strong>Category: </strong><%= event.category.name %><br>
      </div>
    </ul>
  <% end %>

<div id="create_event">
  <%= button_to "Create An Event", new_event_path, method: "get", :class => "edit_button" %>
  <br>
</div>

    <script>
      let all_event_locs = []
    </script>

    <% @events.each do |event| %>
      <script>
        all_event_locs.push({address: "<%= event.location.address %>, New York", type: "<%= event.category.name %>"})
      </script>
    <% end %>


      <!-- MAP BODY CODE -->
      <body>
      <div id='map'></div>
      <script src='https://unpkg.com/es6-promise@4.2.4/dist/es6-promise.auto.min.js'></script>
      <script src="https://unpkg.com/@mapbox/mapbox-sdk/umd/mapbox-sdk.min.js"></script>
      <script>
      mapboxgl.accessToken = 'pk.eyJ1Ijoic2l2YW5hZGxlciIsImEiOiJjanMweHF1dG4xb3FzM3lvM2x1YXgxenk5In0.MyibGT8NsyJQNO-KIzUWcw';
      // eslint-disable-next-line no-undef

      //step one: create the map

      //step two: for each (hint hint) of the elements in the JS array,
      //send a query to the api and create a new marker, adding it to the extisting map
      var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v9',
        center: [-74.012498, 40.703987],
        zoom: 11
      });

      all_event_locs.forEach(function(element){
        iteratorCallBack(element.address, element.type, map)
      });

      //iterate through all_locs array to add markers
      //in the iteration, invoke the helper method below to create a marker for each location's address

      function iteratorCallBack(addressString, type, map){
        var mapboxClient = mapboxSdk({ accessToken: mapboxgl.accessToken });
        mapboxClient.geocoding.forwardGeocode({
          query: addressString,
          autocomplete: false,
          limit: 1
        })
        .send()
        .then(function (response) {
          if (response && response.body && response.body.features && response.body.features.length) {
            var feature = response.body.features[0];
            var color
            if (type == "Happy Hour"){
              color = "red"
            } else if (type == "Escape Room"){
              color = "blue"
            } else if (type == "Park"){
              color = "green"
            } else if (type == "Cats"){
             color = "magenta"
           } else if (type == "Code"){
             color = "purple"
           } else if (type == "Restaurant"){
             color = "yellow"
           } else if (type == "Store"){
             color = "orange"
           } else if (type == "Arcade"){
             color = "cyan"
           } else {
              color = "black"
            }
            return new mapboxgl.Marker({color: color})
              .setLngLat(feature.center)
              .addTo(map);
          }
        });
      }
      </script>
      </body>
      </html>
      <!-- END OF MAP -->
</div>

app/views/events/new.erb
<div class="new_event">
  <div class="header">
    <h1>Create A New Event</h1>
  </div>

  <div class="flash_error">
    <% if !!flash[:errors] %>
      <% flash[:errors].each do |message| %>
        <strong style="color:red;font-family:'Jack Frost'"> <%= message %></strong>
      <% end %>
    <% end %>
  </div>

  <div style="text-align:center" class="new_event">
    <%= form_for @event do |f| %>
      <strong><%= f.label :title %></strong>
      <%= f.text_field :title %><br><br>

      <strong><%= f.label :description %></strong>
      <%= f.text_field :description %><br>

    <div class="new_event">
      <h3>Location For This Event:</h3>
      <%= f.collection_select :location_id, Location.all, :id, :name, {:prompt => "Select Location"} %><br><br>
      <strong style="font-family:'Jack Frost'"><%= f.label "Add a New Location:" %></strong><br>
      <%= fields_for @event.location do |f| %>
        <strong><%= f.label :name %></strong>
        <%= f.text_field :name %><br>
        <strong><%= f.label :address %></strong>
        <%= f.text_field :address %><br>
      <% end %>
    </div>
    <div class="new_event">
      <h3>Category of This Event:</h3>
      <%= f.collection_select :category_id, Category.all, :id, :name, {:prompt => "Select Category"}%><br><br>
      <strong style="font-family:'Jack Frost'"><%= f.label "Add a New Category" %></strong><br>
      <%= fields_for @event.category do |f| %>
        <strong><%= f.label :type %></strong>
        <%= f.text_field :type %>
      <% end %>
      <br><br>
      <%= f.submit "Submit", :class => 'edit_button'%>
      <br><br>
    </div>
      <% end %>

  </div>
</div>

app/views/events/show.erb
<div class="event_show">
  <div class="header">
    <h1> <%= @event.title %> </h1>
  </div>
  <div class="p_container">
    <p><strong>Description:</strong> <%= @event.description %> </p>
    <p><strong>Location: </strong><%= link_to @event.location.name, @event.location, :class => 'links'%> </p>
  </div>
<div class="event_show">
  <h3>Event Achievements</h3>
    <% @event.category.achievements.map do |achievement| %>
      <ul>
        <li><%= link_to achievement.title, achievement, :class => "links"%> --  <%= achievement.description %> -- <%= achievement.points %> Points</li>
      </ul>
    <% end %>
  <strong>Select the Achievements You Completed:</strong>
    <% if !!flash[:notice] %>
      <h4 style="color:green; font-family:'Jack Frost';"><%= flash[:notice] %></h4>
    <% end %>
  <%= form_for @achievement, url: '/achieved', method: "post", :class => "collection_check_boxes" do |f| %>
    <%= hidden_field :event, :id %>
    <div class="check_boxes">
      <%= f.collection_check_boxes :id, @event.category.achievements, :id, :title, {:prompt => "Select Achievements to Complete"} do |b| %>
        <%= b.label class:"check_boxes" do %>
         <%=b.check_box + b.text%>
         <% end %>
      <%end%>
    </div>
    <%= f.submit "Completed", :class => "edit_button"%>
  <% end %>
  <%= button_to "Add Achievements To This Event", new_achievement_path, method: "get", :class => "edit_button" %>
  <br><br>

  <h3>Users Attending</h3>
  <% @event.users.uniq.each do |user| %>
      <ul>
        <li><%= link_to user.username, user, :class => "links" %></li>
      </ul>
  <% end %>
  <br>
  <strong><p>Want to Attend?</p></strong>
  <%= form_for @event, method: "get" do |f| %>
    <%= f.select "user_events", options_for_select(["-- Select Status --", "Attending", "Interested"])%>
    <%= f.submit "Submit", :class => "edit_button"%>
  <% end %>
<br><br>
  <% if current_user.name == "Admin" %>
  <div class="delete_event">
    <%= button_to 'Delete this Event', @event, :class => "edit_button", method: :delete%>
    <br>
  </div>

  <% end %>
</div>

app/views/locations/index.erb
<!-- MAP HEADER -->
<div class="locations">
  <html>
  <head>
  <meta charset='utf-8' />
  <title>Add a marker using a place name</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />
  <style>
  body { margin:0; padding:0; }
  #map { position:fixed; top:0; right:0; bottom:0; width:50%; }
  </style>
  </head>
  <!-- END OF MAP HEADER -->
  <div class="header">
    <h1>All Locations:</h1>
    <div style="border-radius:5px;"class="key">
      <div class="col1">
        <div class="col sm 4" style="background-color:red; width: 100%; height: 35px; vertical-align:center; border: solid white;text-shadow: 0 0 4px black;">Happy Hour</div>
        <div class="col sm 4" style="background-color:magenta; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Cats</div>
        <div class="col sm 4" style="background-color:green; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Park</div>
      </div>
      <div class="col2">
        <div class="col sm 4" style="background-color:blue; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;">Escape Room</div>
        <div class="col sm 4" style="background-color:purple; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Code</div>
        <div class="col sm 4" style="background-color:yellow; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Restaurant</div>
      </div>
      <div class="col3">
        <div class="col sm 4" style="background-color:orange; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Store</div>
        <div class="col sm 4" style="background-color:cyan; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Arcade </div>
        <div class="col sm 4" style="background-color:black; width: 100%; height: 35px; vertical-align:center;border: solid white;text-shadow: 0 0 4px black;padding-top: 5px;">Other</div>
      </div>
    </div>
  </div>
  <% @locations.uniq.each do |location| %>
    <ul>
      <li> <%=link_to location.name, location , :class => "links"%></li>
    </ul>
  <% end %>
<br>
<script>
  let all_event_locs = []
</script>

<% @locations.each do |location| %>
    <% location.events.each do |event| %>
  <script>
    all_event_locs.push({address: "<%= location.address %>, New York", type: "<%= event.category.name %>"})
  </script>
  <% end %>
<% end %>



  <!-- MAP BODY CODE -->
  <body>
  <div id='map'></div>
  <script src='https://unpkg.com/es6-promise@4.2.4/dist/es6-promise.auto.min.js'></script>
  <script src="https://unpkg.com/@mapbox/mapbox-sdk/umd/mapbox-sdk.min.js"></script>
  <script>
  mapboxgl.accessToken = 'pk.eyJ1Ijoic2l2YW5hZGxlciIsImEiOiJjanMweHF1dG4xb3FzM3lvM2x1YXgxenk5In0.MyibGT8NsyJQNO-KIzUWcw';
  // eslint-disable-next-line no-undef

  //step one: create the map

  //step two: for each (hint hint) of the elements in the JS array,
  //send a query to the api and create a new marker, adding it to the extisting map
  var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-74.012498, 40.703987],
    zoom: 11
  });

  all_event_locs.forEach(function(element){
    iteratorCallBack(element.address, element.type, map)
  });

  //iterate through all_locs array to add markers
  //in the iteration, invoke the helper method below to create a marker for each location's address

  function iteratorCallBack(addressString, type, map){
    var mapboxClient = mapboxSdk({ accessToken: mapboxgl.accessToken });
    mapboxClient.geocoding.forwardGeocode({
      query: addressString,
      autocomplete: false,
      limit: 1
    })
    .send()
    .then(function (response) {
      if (response && response.body && response.body.features && response.body.features.length) {
        var feature = response.body.features[0];
        var color
        if (type == "Happy Hour"){
          color = "red"
        } else if (type == "Escape Room"){
          color = "blue"
        } else if (type == "Park"){
          color = "green"
        } else if (type == "Cats"){
         color = "magenta"
       } else if (type == "Code"){
         color = "purple"
       } else if (type == "Restaurant"){
         color = "yellow"
       } else if (type == "Store"){
         color = "orange"
       } else if (type == "Arcade"){
         color = "cyan"
       } else {
          color = "black"
        }
        return new mapboxgl.Marker({color: color})
          .setLngLat(feature.center)
          .addTo(map);
      }
    });
  }
  </script>
  </body>
  </html>
  <!-- END OF MAP -->
</div>

app/views/locations/new.erb
<h1>New Location</h1>
<%= form_for @location do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>

  <%= f.label :address %>
  <%= f.text_field :address %><br><br>

  <% f.submit %>
<% end %>

app/views/locations/show.erb
<!-- MAP HEADER -->
<div class="location_container">
  <html>
  <head>
  <meta charset='utf-8' />
  <title>Add a marker using a place name</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />
  <style>
  body { margin:0; padding:0; }
  #map { position:fixed; top:0; right:0; bottom:0; width:50%; }
  </style>
  </head>
  <!-- END OF MAP HEADER -->

  <h1 class="header"><%= @location.name %> </h1>
  <ul>
    <li><strong>Address:</strong> <%= @location.address %></li>
    <li><strong>Borough: </strong><%= @location.borough %></li>
  </ul>

  <!-- MAP BODY CODE -->
  <body>
  <div id='map'></div>
  <script src='https://unpkg.com/es6-promise@4.2.4/dist/es6-promise.auto.min.js'></script>
  <script src="https://unpkg.com/@mapbox/mapbox-sdk/umd/mapbox-sdk.min.js"></script>
  <script>
  mapboxgl.accessToken = 'pk.eyJ1Ijoic2l2YW5hZGxlciIsImEiOiJjanMweHF1dG4xb3FzM3lvM2x1YXgxenk5In0.MyibGT8NsyJQNO-KIzUWcw';
  // eslint-disable-next-line no-undef
  var mapboxClient = mapboxSdk({ accessToken: mapboxgl.accessToken });
  mapboxClient.geocoding.forwardGeocode({
  query: "<%= @location.address %>, New York",
  autocomplete: false,
  limit: 1
  })
  .send()
  .then(function (response) {
  if (response && response.body && response.body.features && response.body.features.length) {
  var feature = response.body.features[0];

  var map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/mapbox/streets-v9',
  center: feature.center,
  zoom: 10
  });
  new mapboxgl.Marker({color: 'green'})
  .setLngLat(feature.center)
  .addTo(map);
  }
  });
  </script>

  </body>
  </html>
  <!-- END OF MAP -->

  <h3 style="padding:10px;">Events Happening Here:</h3>
  <% @location.events.each do |event| %>
    <ul>
      <li> <%=link_to event.title, event, :class => "links"%>  </li>
    </ul>
  <% end %>

  <br>
</div>

app/views/users/index.erb
<h1>Users</h1>
<% @users.each do |user| %>
<ul>
  <li><%= link_to user.name, user %> </li>
</ul>
<% end %>

app/views/users/show.erb
<div class="header">
  <h1>//<%=@user.username %>  </h1>
</div>
<div id="container">
  <div id="left">
    <img id="avatar" src=" <%= Faker::Avatar.image %>">

    <p class="user_info"><strong>Name: </strong><%=@user.name %> </p>
    <p class="user_info"><strong>Age: </strong><%=@user.age %> </p>
    <br>
    <div id="buttons">
      <% if @user.id == current_user.id || current_user.name == "Admin" %>
        <%= button_to "Edit My Profile", edit_user_path, method: 'get',  :class => 'edit_button'%>
      <% end %><br>
      <% if @user.id == current_user.id %>
        <%= button_to 'Delete Account', user_path(@user), method: :delete, :class => 'edit_button', data: { confirm: 'are u sure lol' } %><br>
        <%= button_to 'Log Out', logout_path, method: :delete, :class => 'edit_button', data: { confirm: 'Want to Logout?'} %>
      <% end %>
      <br>
    </div>
  </div>

  <br>
  <div id="right">
      <h2 class="header">My Achievements:</h2>
      <ul>
        <% @user.achievements.uniq.map do |achievement| %>
          <li class="achievement_info"> <strong><%= achievement.title %> </strong> at
            <% achievement.category.events.map do |event| %>
              <%= event.location.name %>
            <% end %> -- Points: <%= achievement.points %> </li>
        <% end %>
      </ul>
      <div class="header">
        <h4 style="color:green">Total Points: <%= @user.my_achievements %>  </h4>
      </div>
  </div>

</div>

<br>
<div class="events_info">
  <div class="header">
    <h2>My Events:</h2>
  </div>
  <h4>Attending:</h4>
  <% array = [] %>
  <% @user.events.map do |event| %>
    <% event.user_events.map do |ue| %>
      <% if ue.status == "Attending" %>
          <% array << {title: event.title, location: event.location.name, description: event.description} %>
      <% end %>
    <% end %>
  <% end %>
  <% array.uniq.each do |item| %>
    <ul>
      <% @event = Event.find_by(title: item[:title]) %>
      <div class="event_items">
        <%=link_to item[:title], @event, :class => 'links'%><br>
        <strong>Loction: </strong><%= item[:location] %><br>
        <strong>Description: </strong><%= item[:description] %><br>
      </div>
    </ul>
  <% end %>

  <h4>Interested In:</h4>
  <% array = [] %>
  <% @user.events.map do |event| %>
    <% event.user_events.map do |ue| %>
      <% if ue.status == "Interested" %>
          <% array << {title: event.title, location: event.location.name, description: event.description} %>
      <% end %>
    <% end %>
  <% end %>
  <% array.uniq.each do |item| %>
    <ul>
      <% @event = Event.find_by(title: item[:title]) %>
      <div class="event_items">
        <%=link_to item[:title], @event, :class => 'links'%><br>
        <strong>Loction: </strong><%= item[:location] %><br>
        <strong>Description: </strong><%= item[:description] %><br>
      </div>
    </ul>
  <% end %>
</div>

<br>